services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3001:3000
    stdin_open: true
    container_name: frontend_react
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      target: development
    container_name: backend_nodejs
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose: 
      - 3000

  mongo:
    restart: always
    build:
      dockerfile: Dockerfile
      context: "./"
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./collections:/docker-entrypoint-initdb.d
    container_name: mongodb_database
    networks:
      - express-mongo
    expose:
      - 27017

networks:
  react-express:
  express-mongo: